version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-hexa
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    privileged: true
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge
